services:
  - type: web
    name: paddleocr-studio
    runtime: docker
    plan: free
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: OCR_ENGINE
        value: paddle
      - key: OCR_VERSION
        value: PP-OCRv4
      - key: OCR_LANG
        value: en
      - key: OCR_CPU_THREADS
        value: "1"
      - key: MALLOC_ARENA_MAX
        value: "2"
      - key: FLAGS_allocator_strategy
        value: naive
      - key: FLAGS_eager_delete_tensor_gb
        value: "0.0"